-- =========================================================
-- QAQC checklist templates + signoffs
-- =========================================================

create table public.qaqc_checklist_items (
  id uuid primary key default gen_random_uuid(),
  flow text not null,
  stage text not null,
  item_text text not null,
  sort_order int not null
);

create table public.qaqc_signoffs (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references public.sites(id) on delete cascade,
  flow text not null,
  stage text not null,
  identifier text not null default '',
  notes text default '',
  signed_off_by uuid references public.profiles(id),
  signed_off_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.qaqc_signoff_results (
  id uuid primary key default gen_random_uuid(),
  signoff_id uuid not null references public.qaqc_signoffs(id) on delete cascade,
  checklist_item_id uuid not null references public.qaqc_checklist_items(id),
  result qc_result not null default 'na',
  notes text default ''
);

alter table public.qaqc_checklist_items enable row level security;
alter table public.qaqc_signoffs enable row level security;
alter table public.qaqc_signoff_results enable row level security;

create policy "qaqc_items_select_all" on public.qaqc_checklist_items for select to authenticated using (true);

create policy "qaqc_signoffs_select_all" on public.qaqc_signoffs for select to authenticated using (true);
create policy "qaqc_signoffs_insert_authenticated" on public.qaqc_signoffs for insert to authenticated with check (true);
create policy "qaqc_signoffs_update_authenticated" on public.qaqc_signoffs for update to authenticated using (true) with check (true);
create policy "qaqc_signoffs_delete_admin_only" on public.qaqc_signoffs for delete to authenticated using (public.is_admin());

create policy "qaqc_results_select_all" on public.qaqc_signoff_results for select to authenticated using (true);
create policy "qaqc_results_insert_authenticated" on public.qaqc_signoff_results for insert to authenticated with check (true);
create policy "qaqc_results_update_authenticated" on public.qaqc_signoff_results for update to authenticated using (true) with check (true);
create policy "qaqc_results_delete_admin_only" on public.qaqc_signoff_results for delete to authenticated using (public.is_admin());

create index idx_qaqc_signoffs_site_id on public.qaqc_signoffs(site_id);
create index idx_qaqc_results_signoff_id on public.qaqc_signoff_results(signoff_id);
create index idx_qaqc_items_flow_stage on public.qaqc_checklist_items(flow, stage);

-- ---------- Seed checklist template data ----------
insert into public.qaqc_checklist_items (flow, stage, item_text, sort_order) values
  ('SWPPP', 'Silt Fencing', 'Confirm silt fence is upright', 0),
  ('SWPPP', 'Silt Fencing', 'Confirm silt fence is undamaged', 1),
  ('SWPPP', 'Silt Fencing', 'Confirm silt fence meets embedment and projection specs', 2),
  ('SWPPP', 'Silt Fencing', 'Confirm silt fence is trenched in', 3),
  ('SWPPP', 'Silt Fencing', 'Ensure the silt fence is clear of excessive sediment on the fabric', 4),
  ('SWPPP', 'Silt Fencing', 'Confirm sediment build up is less than 1/3 the height of the silt fence', 5),
  ('SWPPP', 'Earth Dikes', 'Confirm earth dikes are compacted', 6),
  ('SWPPP', 'Earth Dikes', 'Confirm earth dikes are undamaged', 7),
  ('SWPPP', 'Earth Dikes', 'Confirm earth dikes are stabilized', 8),
  ('SWPPP', 'Earth Dikes', 'Confirm earth berms direct drainage to an appropriate outlet', 9),
  ('SWPPP', 'Earth Dikes', 'Verify earth dikes are the correct height', 10),
  ('SWPPP', 'Diversion Ditches', 'Confirm diversion ditches are undamaged', 11),
  ('SWPPP', 'Diversion Ditches', 'Confirm diversion ditches are free from sediment buildup', 12),
  ('SWPPP', 'Diversion Ditches', 'Verify that there is no undercutting of the ECB', 13),
  ('SWPPP', 'Diversion Ditches', 'Verify there is no erosion', 14),
  ('SWPPP', 'Sediment Basins', 'Confirm no erosion on basin slopes', 15),
  ('SWPPP', 'Sediment Basins', 'Confirm basins have been seeded', 16),
  ('SWPPP', 'Sediment Basins', 'Confirm basin pipes and baffles are undamaged', 17),
  ('SWPPP', 'Sediment Basins', 'Confirm splash pad is undamaged', 18),
  ('SWPPP', 'Sediment Basins', 'Confirm the fabric is trenched in around the inlets and splash pad', 19),
  ('SWPPP', 'Sediment Basins', 'Verify that built up sediment has been removed', 20),
  ('SWPPP', 'Sediment Basins', 'Confirm baffles are up and in good condition', 21),
  ('SWPPP', 'Sediment Basins', 'Confirm the basin is clear of excess debris', 22),
  ('SWPPP', 'Fiber Rolls', 'Confirm fiber rolls are in place', 23),
  ('SWPPP', 'Fiber Rolls', 'Confirm fiber rolls are trenched in', 24),
  ('SWPPP', 'Fiber Rolls', 'Confirm fiber rolls are staked in every 4''', 25),
  ('SWPPP', 'Fiber Rolls', 'Confirm sediment build-up is not more than 1/2 the height of the fiber roll', 26),
  ('SWPPP', 'Fiber Rolls', 'Turn roll up slope two feet at the end of rows', 27),
  ('SWPPP', 'Fiber Rolls', 'Fiber rolls are placed every 10'' horizontally where slope exceeds 15%', 28),
  ('SWPPP', 'Fiber Rolls', 'Fiber rolls placed at Max. of every 100''', 29),
  ('SWPPP', 'Trash Storage', 'Confirm all designated waste collection areas are correctly located on the map', 30),
  ('SWPPP', 'Trash Storage', 'Verify that all designated waste collection areas are free of leaks and repairs', 31),
  ('SWPPP', 'Trash Storage', 'Ensure all waste collection areas have a lid or cover in case of precipitation', 32),
  ('SWPPP', 'Trash Storage', 'Ensure the field crew is correctly disposing of all personal trash at the end of each day', 33),
  ('SWPPP', 'Trash Storage', 'Verify that the site free from litter', 34),
  ('SWPPP', 'Concrete Washout Area', 'Check the substation and gentie line concrete washout', 35),
  ('SWPPP', 'Concrete Washout Area', 'Verify the area is lined to contain the material from infiltrating into the ground', 36),
  ('SWPPP', 'Concrete Washout Area', 'Verify the washout area is properly bermed with an appropriate BMP (e.g. sandbags, fiber roll, etc.)', 37),
  ('SWPPP', 'Concrete Washout Area', 'Ensure the use of concrete roll off washout bin', 38),
  ('SWPPP', 'Concrete Washout Area', 'Confirm for the use of proper material for the liner, void of holes and tears', 39),
  ('SWPPP', 'Concrete Washout Area', 'Confirm the washout area is properly sized to completely contain all liquid and waste concrete material (minimum 10ft by 10ft)', 40),
  ('SWPPP', 'Concrete Washout Area', 'Verify the washout area is located more than 50ft from any storm drain inlets, watercourses, and construction traffic', 41),
  ('SWPPP', 'Seeding', 'Is additional seeding needed in any areas?', 42),
  ('SWPPP', 'Turf Mats', 'Confirm Turf Mats are Installed per Specs', 43),
  ('SWPPP', 'Turf Mats', 'Confirm Turf Mats are Undamaged', 44),
  ('SWPPP', 'Vehicle Entrances', 'Confirm there is no dirt is tracked outside of the project', 45),
  ('SWPPP', 'Vehicle Entrances', 'Confirm rumble plates are in place at entrances', 46),
  ('SWPPP', 'Vehicle Entrances', 'Verify the rock is not overly compacted', 47),
  ('SWPPP', 'Vehicle Entrances', 'Verify there is minimal sedimentation', 48),
  ('SWPPP', 'Vehicle Entrances', 'Confirm street sweeper is operating as necessary', 49),
  ('SWPPP', 'Fueling Stations', 'Confirm spill kits are present', 50),
  ('SWPPP', 'Fueling Stations', 'Confirm drip pans are present', 51),
  ('SWPPP', 'Fueling Stations', 'Confirm there are no visible spills', 52),
  ('SWPPP', 'Fueling Stations', 'Verify the tanks have a secondary containment capable of storing 110% of the volume', 53),
  ('SWPPP', 'Straw Bales', 'Confirm the straw bale is undamaged', 54),
  ('SWPPP', 'Straw Bales', 'Confirm the straw bale in stake in', 55),
  ('SWPPP', 'Straw Bales', 'Confirm the straw bales arced around the outflow', 56),
  ('SWPPP', 'Laydown Yard', 'Ensure the laydown yard is completely encompassed with BMPs (earth berm, fiber rolls, silt fence, etc.)', 57),
  ('SWPPP', 'Laydown Yard', 'Ensure drip pans are placed beneath all equipment at the end of the day', 58),
  ('SWPPP', 'Laydown Yard', 'Verify that no chemicals are stored in the laydown yard', 59),
  ('SWPPP', 'Check Dams', 'Confirm check dam is undamaged and built to specs', 60),
  ('SWPPP', 'Check Dams', 'Confirm no debris is blocking the check dam', 61),
  ('SWPPP', 'Check Dams', 'Verify the spacing is correct', 62),
  ('SWPPP', 'Check Dams', 'Ensure sediment build up is cleared out behind check dams', 63),
  ('SWPPP', 'Check Dams', 'Confirm the check dams are curved', 64),
  ('SWPPP', 'Water Tank', 'Ensure all water tanks are on site and within the site BMPs', 65),
  ('SWPPP', 'Restrooms', 'Ensure that all restrooms are appropriately located on the map', 66),
  ('SWPPP', 'Restrooms', 'Verify that all restrooms have a secondary containment', 67),
  ('SWPPP', 'Restrooms', 'Confirm that all restrooms are tied down', 68),
  ('Civil', 'Grading', 'Confirm no erosion is present', 69),
  ('Civil', 'Grading', 'Confirm temporary or permanent stabilized is present', 70),
  ('Civil', 'Grading', 'Confirm exposed areas are stabilized within 14 days or ASAP', 71),
  ('Civil', 'Fence Fabric', 'Survey Location', 72),
  ('Civil', 'Fence Fabric', 'Post Spacing', 73),
  ('Civil', 'Fence Fabric', 'Depth of post foundation', 74),
  ('Civil', 'Fence Fabric', 'Post plumbness', 75),
  ('Civil', 'Fence Fabric', 'Post height', 76),
  ('Civil', 'Fence Fabric', 'Distance from fabric to grade', 77),
  ('Civil', 'Road Sub-grade', 'Confirm roads have no erosion present', 78),
  ('Foundations', 'Piles', 'Type of Pier (size and coating)', 79),
  ('Foundations', 'Piles', 'Type of Pier (Array or Motor)', 80),
  ('Foundations', 'Piles', 'Top of Pier Row Spacing (N - S)', 81),
  ('Foundations', 'Piles', 'Top of Pier Row Spacing (E - W)', 82),
  ('Foundations', 'Piles', 'Top of Pier Elevation', 83),
  ('Foundations', 'Piles', 'Pier Twist', 84),
  ('Foundations', 'Piles', 'Pier Plumb (E - W)', 85),
  ('Foundations', 'Piles', 'Pier Plumb (N - S)', 86),
  ('Foundations', 'Piles', 'Row Slope (N - S)', 87),
  ('Foundations', 'Piles', 'Top of Pier Damage', 88),
  ('Foundations', 'Piles', 'Safety Precautions', 89),
  ('Foundations', 'Pile Survey', 'Grading', 90),
  ('Foundations', 'Pile Survey', 'Row Spacing (N-S)', 91),
  ('Foundations', 'Pile Survey', 'Row Spacing (E-W)', 92),
  ('Foundations', 'Pile Survey', 'Feather Color (Type of Pier)', 93),
  ('Rows', 'Torque Tubes', 'Tube Size/ Length/ Orientation', 94),
  ('Rows', 'Torque Tubes', 'Verify torque tube color', 95),
  ('Rows', 'Torque Tubes', 'Verify tube to tube angle is w/in tolerance', 96),
  ('Rows', 'Torque Tubes', 'Verify no physical damage', 97),
  ('Rows', 'Modules', 'Verify Module Wattage is Correct for Location', 98),
  ('Rows', 'Modules', 'Verify Module is not Visually Damaged', 99),
  ('Rows', 'Modules', 'Check Module to Module Spacing', 100),
  ('Rows', 'Modules', 'Ensure Proper Module Orientation', 101),
  ('Rows', 'Modules', 'Verify all Module Hardware is in Place', 102),
  ('Rows', 'String Wiring', 'Verify all Connections are Fully Clicked', 103),
  ('Rows', 'String Wiring', 'Verify Proper Ties', 104),
  ('Rows', 'String Wiring', 'Verify Correct Wire Type', 105),
  ('Rows', 'String Wiring', 'Verify No Visual Damage', 106),
  ('Rows', 'String Wiring', 'Verify No Excess or Loose Wire', 107),
  ('Rows', 'String Wiring', 'Verify the Correct Number of Modules are Plugged In', 108),
  ('Rows', 'Finish Racking', 'Slew gear orientation, Bracket pins fully swaged', 109),
  ('Rows', 'Finish Racking', 'Confirm Slew gear Bracket bolt torque/mark', 110),
  ('Rows', 'Finish Racking', 'Verify motor orientation and cap screw torque', 111),
  ('Rows', 'Finish Racking', 'Motor antenna mount and antenna', 112),
  ('Rows', 'Finish Racking', 'Bearing Housing Assembly Pin Orientation, properly swaged pins', 113),
  ('Rows', 'Finish Racking', 'Tube sizes/Lengths/Orientation', 114),
  ('Rows', 'Finish Racking', 'Tube Rivets fully fastened, quantity', 115),
  ('Rows', 'Finish Racking', 'Confirm All BOM pins are treated with Cold Galvinization', 116),
  ('Rows', 'Finish Racking', 'Bearing Housing Assembly Rails positioned correctly and torqued/marked', 117),
  ('Rows', 'Finish Racking', 'Row Aligned and Secured per  Nextracker Temperature Criteria', 118),
  ('Rows', 'Finish Racking', 'module clamp & quantities staged for module install, bottom clamp fastner torqued/marked', 119),
  ('Rows', 'Finish Racking', 'Dampener quantity per row type', 120),
  ('Rows', 'Finish Racking', 'Dampener assembly installed and torqued/ marked', 121),
  ('Rows', 'Finish Racking', 'Power Converter bracket and assembly installed correctly', 122),
  ('Rows', 'Finish Racking', 'controller assembly installed', 123),
  ('Rows', 'Finish Racking', '120 Degree Tracking Range', 124),
  ('Rows', 'Finish Racking', 'Safety Precautions', 125),
  ('AC', 'MV Trenching', 'Verify Trenching Width and Depth per plans', 126),
  ('AC', 'MV Trenching', 'Verify Trenching is Free of Rock/Debris Prior to Placement of Cable', 127),
  ('AC', 'MV Cable', 'Verify AC Conductor Size and Quantity per plans', 128),
  ('AC', 'MV Cable', 'Verify Horizontal Spacing and Conductors per plans', 129),
  ('AC', 'MV Cable', 'Confirm All Conductors are not Visually Damaged', 130),
  ('AC', 'MV Backfill', 'Verify Warning Tape is Properly Placed', 131),
  ('AC', 'MV Backfill', 'Verify Compaction is Per Plan', 132),
  ('AC', 'MV Backfill', 'Verify conductors are vertically spaced per plan', 133),
  ('AC', 'MV Backfill', 'Verify compaction via third party inspector four times per linear mile, or at least once per trench circuit', 134),
  ('DC', 'DC Trenching', 'Verify Trenching Width and Depth per plans', 135),
  ('DC', 'DC Trenching', 'Verify Trenching is Free of Rock/Debris Prior to Placement of Cable', 136),
  ('DC', 'DC Backfill', 'Verify Warning Tape is Properly Placed', 137),
  ('DC', 'DC Backfill', 'Verify Compaction is Per Plan', 138),
  ('DC', 'DC Backfill', 'Verify conductors are vertically spaced per plan', 139),
  ('DC', 'DC Backfill', 'Verify compaction via third party inspector four times per linear mile, or at least once per trench circuit', 140),
  ('DC', 'Disconnects', 'Verify Disconnect Box is free of visual damage', 141),
  ('DC', 'Disconnects', 'Verify Disconnect Box is free of debris', 142),
  ('DC', 'Disconnects', 'Verify Disconnect Box is above minimum elevation', 143),
  ('DC', 'Disconnects', 'Verify all Hardware is Installed and Fastened', 144),
  ('DC', 'Disconnects', 'Verify Box Labeling & Orientation per IFC', 145),
  ('DC', 'Disconnects', 'Verify Correct Feeder', 146),
  ('DC', 'Disconnects', 'Verify Box Spacing', 147),
  ('DC', 'Disconnects', 'Verify labels & warning stickers have been placed', 148),
  ('DC', 'Disconnects', 'Verify Torque Marks', 149),
  ('DC', 'Disconnect Box Termination', 'Verify Disconnect Term is free of visual damage', 150),
  ('DC', 'Disconnect Box Termination', 'Verify Disconnect Termis free of debris', 151),
  ('DC', 'Disconnect Box Termination', 'Verify Disconnect Term is above minimum elevation', 152),
  ('DC', 'Disconnect Box Termination', 'Verify all Hardware is Installed and Fastened', 153),
  ('DC', 'Disconnect Box Termination', 'Verify Correct Feeder and width size', 154),
  ('DC', 'Disconnect Box Termination', 'Verify Torque Marks and specs', 155),
  ('DC', 'DC Cable', 'Verify DC Conductor Size and Quantity', 156),
  ('DC', 'DC Cable', 'Verify Horizontal Spacing and Conductors per plans', 157),
  ('DC', 'DC Cable', 'Verify All Conductors are not Visually Damaged', 158),
  ('Inverters', 'Plates Welding', 'Inspect prior to welding per Table N5.4-1, AISC 360-10.', 159),
  ('Inverters', 'Plates Welding', 'Verify welding procedure specifications (WPS) and consumable certificates.', 160),
  ('Inverters', 'Plates Welding', 'Identify proper material.', 161),
  ('Inverters', 'Plates Welding', 'Inspect welder identification and certifications.', 162),
  ('Inverters', 'Plates Welding', 'Inspect fit-up of 3/16” fillet welds.', 163),
  ('Inverters', 'Plates Welding', 'Inspect during welding per Table N5.4-1, AISC 360-10', 164),
  ('Inverters', 'Plates Welding', 'Observe control and handling of welding consumables.', 165),
  ('Inverters', 'Plates Welding', 'Verify environmental conditions within limits of AWS.', 166),
  ('Inverters', 'Plates Welding', 'Ensure WPS Followed.', 167),
  ('Inverters', 'Plates Welding', 'Inspect welding techniques.', 168),
  ('Inverters', 'Plates Welding', 'Inspect after welding per Table N5.4-1, AISC 360-10.', 169),
  ('Inverters', 'Plates Welding', 'Welds are cleaned.', 170),
  ('Inverters', 'Plates Welding', 'Size, length, & location of welds.', 171),
  ('Inverters', 'Plates Welding', 'Welds meet visual acceptance criteria.', 172),
  ('Inverters', 'DC Trenching', 'Verify Trenching Width and Depth per plans', 173),
  ('Inverters', 'DC Trenching', 'Verify Trenching is Free of Rock/Debris Prior to Placement of Cable', 174),
  ('Inverters', 'DC Conduit', 'Verify Conduit Size and Quantity', 175),
  ('Inverters', 'DC Conduit', 'Verify Conduits are not Visually Damaged', 176),
  ('Inverters', 'DC Wiring', 'Verify Conductor Size and Quantity', 177),
  ('Inverters', 'DC Wiring', 'Verify Conductor Spacing', 178),
  ('Inverters', 'DC Wiring', 'Verify all conductors are not visually damaged', 179),
  ('Inverters', 'DC Backfill', 'Verify Compaction is Per Plan four times per linear mile, or at least once per trench circuit', 180),
  ('Inverters', 'DC Backfill', 'Verify Warning Tape is Properly Placed', 181),
  ('Inverters', 'DC Backfill', 'Verify Wire Type is Correct per Blymyer', 182),
  ('Inverters', 'Ground Trenching', 'Verify Grounding Depth per plans', 183),
  ('Inverters', 'Ground Trenching', 'Verify Trench is Free of Rock/Debris', 184),
  ('Inverters', 'Ground Wiring', 'Verify Correct Size Ground Wire', 185),
  ('Inverters', 'Ground Wiring', 'Verify Ground Ring Connection', 186),
  ('Inverters', 'Ground Wiring', 'Verify Depth of Ground Rod', 187),
  ('Inverters', 'Ground Wiring', 'Verify proper grounding termination', 188),
  ('Inverters', 'Ground Backfill', 'Verify Compaction is Per plan', 189),
  ('Inverters', 'AC/Fiber Trenching', 'Verify Trenching Width and Depth per plans', 190),
  ('Inverters', 'AC/Fiber Trenching', 'Verify Trenching is Free of Rock/Debris Prior to Placement of Cable', 191),
  ('Inverters', 'AC/Fiber Conduit', 'Verify Conduit Size and Quantity', 192),
  ('Inverters', 'AC/Fiber Conduit', 'Verify Conduits are not Visually Damaged', 193),
  ('Inverters', 'AC/Fiber Wiring', 'Verify Fiber Cable Conductor Size and Quantity', 194),
  ('Inverters', 'AC/Fiber Wiring', 'Verify Fiber Cable Conductor Spacing from AC Conductor', 195),
  ('Inverters', 'AC/Fiber Backfill', 'Verify Warning Tape is Properly Placed', 196),
  ('Inverters', 'AC/Fiber Backfill', 'Verify Compaction is Per Plan, four times per linear mile, or at least once per trench circuit', 197),
  ('Inverters', 'AC/Fiber Backfill', 'Verify Wire Type is Correct per Blymyer', 198),
  ('Inverters', 'Skid Landing', 'Verify correct serial number is landed in correct location', 199),
  ('Inverters', 'I.E.S Welding', 'Verify plates are welded to inverters with field fillet welds', 200),
  ('Inverters', 'I.E.S Welding', 'Verify plates are bolted to inverter skid', 201),
  ('Inverters', 'DC Termination', 'Cable Properly Labeled', 202),
  ('Inverters', 'DC Termination', 'Cable Properly Seated in Lugs', 203),
  ('Inverters', 'DC Termination', 'Proper Contact between Lug and Bus Bar', 204),
  ('Inverters', 'DC Termination', 'Lugs are Properly Torqued and Marked', 205),
  ('Inverters', 'DC Termination', 'Confirm phasing is correct', 206),
  ('Inverters', 'DC Termination', 'Confirm correct cable qty', 207),
  ('Inverters', 'DC Termination', 'Confirm cable sizing', 208),
  ('Inverters', 'AC Termination', 'Cable Properly Labeled', 209),
  ('Inverters', 'AC Termination', 'Cable Properly Seated in Lugs', 210),
  ('Inverters', 'AC Termination', 'Proper Contact between Lug and Bus Bar', 211),
  ('Inverters', 'AC Termination', 'Lugs are Properly Torqued and Marked', 212),
  ('Inverters', 'AC Termination', 'Cable properly seated in termination slots', 213),
  ('Inverters', 'AC Termination', 'Proper contact between MV conductors and termination slot', 214),
  ('Inverters', 'AC Termination', 'Confirm phasing is correct', 215),
  ('Inverters', 'AC Termination', 'Confirm correct cable qty', 216),
  ('Inverters', 'AC Termination', 'Confirm cable sizing', 217),
  ('Inverters', 'AC Termination', 'Confirm grounding busbar is installed on the barrier', 218),
  ('Inverters', 'Fiber Termination', 'Verify Fiber Quantities', 219),
  ('Inverters', 'Fiber Termination', 'Verify Fiber Lengths', 220),
  ('Inverters', 'Fiber Termination', 'Verify Fiber is not Visually Damaged', 221),
  ('Inverters', 'Rock Pads', 'Verify Rock Size', 222),
  ('Inverters', 'Rock Pads', 'Verify Rock Goes to Base of Skid', 223),
  ('Inverters', 'Rock Pads', 'Verify Width and Depth of Rock Placement', 224),
  ('SCADA', 'FNE', 'Verify SCADA Rack Equipment is free of visual damage', 225),
  ('SCADA', 'FNE', 'Verify all hardware is installed', 226),
  ('SCADA', 'FNE', 'Verify labeling is correct', 227),
  ('SCADA', 'FNE', 'Verify the Correct SCADA Rack is in the Correct Location', 228),
  ('SCADA', 'FNE', 'Verify Plate Size', 229),
  ('SCADA', 'FNE', 'Verify Welded Plates are Installed and Level', 230),
  ('SCADA', 'FNE', 'Verify Plates have Field Fillet Welds', 231),
  ('SCADA', 'FNE Mount', 'Verify SCADA Rack Equipment is free of visual damage', 232),
  ('SCADA', 'FNE Mount', 'Verify all hardware is installed', 233),
  ('SCADA', 'FNE Mount', 'Verify labeling is correct', 234),
  ('SCADA', 'FNE Mount', 'Verify the Correct SCADA Rack is in the Correct Location', 235),
  ('SCADA', 'FNE Mount', 'Verify Plate Size', 236),
  ('SCADA', 'FNE Mount', 'Verify Welded Plates are Installed and Level', 237),
  ('SCADA', 'FNE Mount', 'Verify Plates have Field Fillet Welds', 238);
